services:
  backend:
    image: ghcr.io/ricardoalcantara/api-email-client-backend:latest
    # ports:
    #   - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped
    

  frontend:
    image: ghcr.io/ricardoalcantara/api-email-client-frontend:latest
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./frontend/docker/default.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - BACKEND_URL=http://backend:5555

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api_email_client
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  mailhog:
    image: mailhog/mailhog
    restart: always
    profiles:
      - tester
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  postgres_data:
