name: Build and Push Docker Images

on:
  push:
    tags:
      - 'v*'

jobs:
  docker_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: backend
            context: .
          - name: frontend
            context: ./frontend
    steps:
      - name: Extract tag name
        shell: bash
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        id: extract_tag

      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push GitHub
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/ricardoalcantara/${{ github.event.repository.name }}-${{ matrix.name }}:${{ steps.extract_tag.outputs.tag }}
            ghcr.io/ricardoalcantara/${{ github.event.repository.name }}-${{ matrix.name }}:latest